### PR TITLE
Code Review

### PR DESCRIPTION
**Pull request by jameskempf**

### CODE REVIEW

**Comment by eanyanwu** [comment]
Hmm...I could not find any files under _Files changed_.

**Comment by jameskempf** [comment]
Even if there are no files under Files Changed, are you able to access and read my code?

**Comment by compassface** [comment]
can't find it, I mean yes I can see it in the code tab but I am unable to edit unless i fork the repo

**Comment by jameskempf** [comment]
My code ended up in "Merge remote-tracking branch 'origin/master'" in the commits tab above. I believe you can add comments to that. If not, you can just leave your comments here.

**Comment by eanyanwu** [comment]
Ahh, found it! Will comment later tonight. Thanks :+1:

**Comment by eanyanwu** [comment]
Looks good James! Your code is well structured and compartmentalized. Easy to understand what each part of the javascript files do and how they link to each other. 
Keep it up!

**Comment by compassface** [comment]
Looks good, One small suggestion would be to point out the changes in your code if it's up for review specify the files. It will help give incentive to the reviewer to take a closer look.

**Pull request merged**
